- name: Add yum repos
  yum_repository:
    name: "{{ item.name }}"
    description: "{{ item.description }}"
    file: "{{ item.file }}"
    baseurl: "{{ item.baseurl }}"
    enabled: true
    gpgkey: "{{ item.gpgkey }}"
    gpgcheck: true
    state: present
  loop:
    - {
      name: "Kubernetes",
      description: "Kubernetes",
      file: "kubernetes",
      baseurl: "http://yum.kubernetes.io/repos/kubernetes-el7-x86_64",
      gpgkey: "https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg"
    }
    - {
      name: "Docker",
      description: "Docker",
      file: "docker",
      baseurl: "https://download.docker.com/linux/centos/7/x86_64/stable",
      gpgkey: "https://download.docker.com/linux/centos/gpg"
    }

# install docker-selinux package separately to avoid obsoletion errors from newer docker releases
- name: Remove container-selinux
  yum:
    name: container-selinux
    state: absent

- name: Install docker selinux package # need to avoid installing obsolete packages
  environment: "{{ proxy_env }}"
  shell: "yum -y --setopt=obsoletes=0 install docker-ce-selinux-{{ docker_version }}"
  tags:
    - skip_ansible_lint

- name: Install required packages
  environment: "{{ proxy_env }}"
  yum:
    name: "{{ item }}"
    state: present
  loop:
    - "docker-ce-{{ docker_version }}"
    - "socat"

- name: Ensure sensu monitoring script folder exists
  file:
    state: directory
    path: /etc/sensu/plugins/metrics/nais

- name: Ensure sensu monitoring scripts exist
  copy:
    src: "files/sensu/checks/{{ item }}"
    dest: "/etc/sensu/plugins/metrics/nais/{{ item }}"
    mode: 0775
  loop:
    - aggregate-metrics.sh
    - addon-metrics.sh
    - component-metrics.sh
    - interface-metrics.sh
    - nodes-metrics.sh
    - process-metrics.sh
  notify:
    - restart_sensu

- name: Add puppet facts for master nodes
  template:
    src: templates/puppet-facts.master.j2
    dest: /etc/puppetlabs/facter/facts.d/nais.yaml
  when: "'masters' in group_names"

- name: Copy sensu client.json with correct master node config
  template:
    src: templates/sensu/master-client.json.j2
    dest: /etc/sensu/conf.d/client.json
  when: "'masters' in group_names"
  notify:
    - restart_sensu

- name: Ensure sensu monitoring config for master node exists
  copy:
    src: files/sensu/config/nais_master_metrics.json
    dest: /etc/sensu/conf.d/nais_master_metrics.json
  when: "'masters' in group_names"
  notify:
    - restart_sensu

- name: Add puppet facts for worker nodes
  template:
    src: templates/puppet-facts.worker.j2
    dest: /etc/puppetlabs/facter/facts.d/nais.yaml
  when: "'workers' in group_names"

- name: Copy sensu client.json with correct worker node config
  template:
    src: templates/sensu/worker-client.json.j2
    dest: /etc/sensu/conf.d/client.json
  when: "'workers' in group_names"
  notify:
    - restart_sensu

- name: Ensure sensu monitoring config for worker nodes exist
  copy:
    src: files/sensu/config/nais_worker_metrics.json
    dest: /etc/sensu/conf.d/nais_worker_metrics.json
  when: "'workers' in group_names"
  notify:
    - restart_sensu

- name: Ensure rbd kernel module is present
  modprobe:
    name: rbd
    state: present

- name: Load rbd kernel module on boot
  copy:
    src: files/rbd.modules
    dest: /etc/sysconfig/modules/rbd.modules
    mode: 0755

