- name: Ensure directories exist
  file:
    state: directory
    path: "{{ item }}"
  loop:
    - /etc/kubernetes/kubeconfigs
    - /etc/kubernetes/pki
    - /etc/systemd/system/docker.service.d
    - /etc/docker
    - "{{ install_dir }}/bin"
    - "{{ install_dir }}/libexec"

- name: Docker proxy settings
  template:
    src: "{{ role_path }}/templates/docker-proxy.conf.j2"
    dest: /etc/systemd/system/docker.service.d/proxy.conf
  when: nais_http_proxy is defined


