- hosts: localhost
  tasks:
  - name: Add pool member to first bigip
    check_mode: yes
    poll: 0
    when:
    - bigip_pool_name is defined
    - bigip_partition is defined
    delegate_to: localhost
    bigip_pool_member:
      state: present
      partition: "{{ bigip_partition }}"
      provider:
        server: "{{ bigip_address }}"
        timeout: 10
        validate_certs: no
      pool: "{{ bigip_pool_name }}"
      aggregate: "{{ lookup('template', 'bigip_aggregate_members.yaml.j2') | from_yaml }}"
      replace_all_with: yes
