- hosts: localhost
  vars:
    provider:
      server: "{{ bigip_address }}"
      user: "{{ lookup('env','F5_USER') }}"
      password: "{{ lookup('env','F5_PASSWORD') }}"
      timeout: 10
      validate_certs: no
  tasks:
  - name: Add pool member to first bigip
    when:
    - bigip_pool_name is defined
    - bigip_partition is defined
    delegate_to: localhost
    bigip_pool_member:
      state: present
      partition: "{{ bigip_partition }}"
      provider: "{{ provider }}"
      pool: "{{ bigip_pool_name }}"
      aggregate: "{{ lookup('template', 'bigip_aggregate_members.yaml.j2') | from_yaml }}"
      replace_all_with: yes

  - name: Whitelist hosts
    when:
    - bigip_navtunnel_whitelist_dg is defined
    - bigip_partition is defined
    bigip_data_group:
      provider: "{{ provider }}"
      name: "{{ bigip_navtunnel_whitelist_dg }}"
      partition: "{{ bigip_partition }}"
      records_src: "inventory/bigip_dg/{{ bigip_navtunnel_whitelist_dg }}"
