- hosts: localhost
  tasks:
  - name: Add pool member to first bigip
    ignore_errors: true
    poll: 0
    when:
    - bigip_pool_name is defined
    - bigip_partition is defined
    delegate_to: localhost
    bigip_pool_member:
      state: present
      partition: "{{ bigip_partition }}"
      provider:
        server: "{{ bigip_address }}"
        timeout: 10
        validate_certs: no
      pool: "{{ bigip_pool_name }}"
      host: "{{ lookup('dig', item) }}"
      port: 443
    loop: "{{ query('inventory_hostnames', 'workers:!storage_nodes') }}"
