- hosts: etcd
  user: "{{ remote_user }}"
  become: yes
  tasks:
    - name: Etcd
      systemd:
        daemon_reload: yes
        name: etcd.service
        state: stop
      ignore_errors: yes

    - name: Remove old cache
      command: rm -r /var/lib/etcd/
