- hosts: all:!etcd
  user: "{{ remote_user }}"
  become: yes
  tasks:
    - name: Kubelet
      systemd:
        daemon_reload: yes
        name: kubelet.service
        state: restarted
    - name: Kube-proxy
      systemd:
        daemon_reload: yes
        name: kube-proxy.service
        state: restarted
    - name: Docker
      systemd:
        daemon_reload: yes
        name: docker.service
        state: restarted
    - name: Flannel
      systemd:
        daemon_reload: yes
        name: flannel.service
        state: restarted
      ignore_errors: yes

- hosts: etcd
  user: "{{ remote_user }}"
  become: yes
  tasks:
    - name: Etcd
      systemd:
        daemon_reload: yes
        name: etcd.service
        state: restarted
      ignore_errors: yes
