- hosts: prometheus
  gather_facts: False
  user: "{{ remote_user }}"
  any_errors_fatal: true
  roles:
    - coreos_bootstrap
  pre_tasks:
  - name: Copy python interpreter to server
    delegate_to: localhost
    command: "scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null {{ lookup('env', 'SSH_OPTS') }} files/pypy2.7-v7.3.1-linux64.tar.bz2 {{ remote_user }}@{{ inventory_hostname }}:/home/{{ remote_user }}/"
    changed_when: false

- hosts: prometheus
  user: "{{ remote_user }}"
  become: yes
  roles:
  -  { role: proxy, when: nais_http_proxy is defined }
  - os-users
  - logs
  - update-engine
  - node_exporter
  - prometheus
  tasks:
    - name: Ensure locksmithd is started
      systemd:
        daemon_reload: yes
        name: locksmithd.service
        state: started
        enabled: yes

    - name: Render and copy /etc/resolv.conf
      template:
        src: templates/resolv.conf.j2
        dest: /etc/resolv.conf

    - name: Add systemd unit to fix issue 32728 (symlinks in /sys)
      copy:
        src: files/kube-issue-32728-fix.service
        dest: /etc/systemd/system/kube-issue-32728-fix.service
        owner: root
        group: root
        mode: 0644

    - name: Enable the fix for 32728 during boot
      systemd:
        daemon_reload: yes
        name: kube-issue-32728-fix.service
        state: started
        enabled: yes

    - name: Add nsswitch.conf
      copy:
        src: "files/nsswitch.conf"
        dest: "/etc/nsswitch.conf"
