- name: Fetch Etcd certificates
  #include_tasks: "{{ role_path }}/tasks/fetch_if_exists.yaml"
  fetch:
    src: "{{ src_path }}/{{ item }}"
    dest: "{{ dest_path }}/"
    flat: yes
  loop:
    - etcd-client.pem
    - etcd-client-key.pem
    - server.pem
    - server-key.pem
  vars:
    src_path: /etc/ssl/etcd
    dest_path: target/pki/etcd
  run_once: true

- name: Fetch Etcd peer-certificates
  #include_tasks: "{{ role_path }}/tasks/fetch_if_exists.yaml"
  fetch:
    src: "{{ src_path }}/{{ item }}"
    dest: "{{ dest_path }}/"
    flat: yes
  loop:
    - "peer-{{ ansible_hostname }}.pem"
    - "peer-{{ ansible_hostname }}-key.pem"
  vars:
    src_path: /etc/ssl/etcd
    dest_path: target/pki/etcd
