- name: Check master for CA cert
  stat:
    path: /etc/kubernetes/pki/ca.pem
  register: ca

- name: Check master for RequestHeader client CA cert
  stat:
    path: /etc/kubernetes/pki/requestheader-client-ca.pem
  register: requestheaderclientca

- name: Check master for api-server-server cert
  stat:
    path: /etc/kubernetes/pki/kube-apiserver-server.pem
  register: apiserver

- name: Check master for service account key
  stat:
    path: /etc/kubernetes/pki/sa.key
  register: sa

- name: Check master for admin cert
  stat:
    path: /etc/kubernetes/pki/admin.pem
  register: admin

- name: Check master for aggregator cert
  stat:
    path: /etc/kubernetes/pki/aggregator.pem
  register: aggregator

- name: Check master for etcd.pem
  stat:
    path: /etc/kubernetes/pki/etcd/etcd.pem
  register: etcd

- name: Check master for etcd-key.pem
  stat:
    path: /etc/kubernetes/pki/etcd/etcd-key.pem
  register: etcd-key

- name: Fetch ca.pem
  fetch:
    src: /etc/kubernetes/pki/ca.pem
    dest: target/pki/
    flat: yes
  when: ca.stat.exists

- name: Fetch etcd.pem
  fetch:
    src: /etc/kubernetes/pki/etcd/etcd.pem
    dest: target/pki/etcd/
    flat: yes
  when: etcd.stat.exists

- name: Fetch etcd-key.pem
  fetch:
    src: /etc/kubernetes/pki/etcd/etcd-key.pem
    dest: target/pki/etcd/
    flat: yes
  when: etcd-key.stat.exists

- name: Fetch ca-key.pem
  fetch:
    src: /etc/kubernetes/pki/ca-key.pem
    dest: target/pki/
    flat: yes
  when: ca.stat.exists

- name: Fetch requestheader-client-ca.pem
  fetch:
    src: /etc/kubernetes/pki/requestheader-client-ca.pem
    dest: target/pki/
    flat: yes
  when: requestheaderclientca.stat.exists

- name: Fetch requestheader-client-ca-key.pem
  fetch:
    src: /etc/kubernetes/pki/requestheader-client-ca-key.pem
    dest: target/pki/
    flat: yes
  when: requestheaderclientca.stat.exists

- name: Fetch admin.pem
  fetch:
    src: /etc/kubernetes/pki/admin.pem
    dest: target/pki/
    flat: yes
  when: admin.stat.exists

- name: Fetch admin-key.pem
  fetch:
    src: /etc/kubernetes/pki/admin-key.pem
    dest: target/pki/
    flat: yes
  when: admin.stat.exists

- name: Fetch aggregator.pem
  fetch:
    src: /etc/kubernetes/pki/aggregator.pem
    dest: target/pki/
    flat: yes
  when: aggregator.stat.exists

- name: Fetch aggregator-key.pem
  fetch:
    src: /etc/kubernetes/pki/aggregator-key.pem
    dest: target/pki/
    flat: yes
  when: aggregator.stat.exists

- name: Fetch kube-apiserver-server.pem
  fetch:
    src: /etc/kubernetes/pki/kube-apiserver-server.pem
    dest: target/pki/
    flat: yes
  when: apiserver.stat.exists

- name: Fetch kube-apiserver-server-key.pem
  fetch:
    src: /etc/kubernetes/pki/kube-apiserver-server-key.pem
    dest: target/pki/
    flat: yes
  when: apiserver.stat.exists

- name: Fetch sa.key
  fetch:
    src: /etc/kubernetes/pki/sa.key
    dest: target/pki/
    flat: yes
  when: sa.stat.exists

- name: Fetch sa.pub
  fetch:
    src: /etc/kubernetes/pki/sa.pub
    dest: target/pki/
    flat: yes
  when: sa.stat.exists
