- name: Fetch certificates on master node
  include_tasks: "{{ role_path }}/tasks/fetch_if_exists.yaml"
  loop:
    - ca.pem
    - ca-key.pem
    - front-proxy-ca.pem
    - front-proxy-ca-key.pem
    - kube-apiserver-server.pem
    - kube-apiserver-server-key.pem
    - sa.pub
    - sa.key
    - admin.pem
    - admin-key.pem
    - front-proxy-client.pem
    - front-proxy-client-key.pem
  vars:
    src_path: /etc/kubernetes/pki
    dest_path: target/pki

- name: Fetch etcd client-certificates
  include_tasks: "{{ role_path }}/tasks/fetch_if_exists.yaml"
  loop:
    - etcd-client.pem
    - etcd-client-key.pem
  vars:
    src_path: /etc/kubernetes/pki
    dest_path: target/pki/etcd
  tags:
    - fetch_etcd_certs
