- name: Fetch certificates on master node
  include_tasks: "{{ role_path }}/tasks/fetch_if_exists.yaml"
  with_items:
    - ca.pem
    - ca-key.pem
    - requestheader-client-ca.pem
    - requestheader-client-ca-key.pem
    - kube-apiserver-server.pem
    - kube-apiserver-server-key.pem
    - sa.pub
    - sa.key
    - admin.pem
    - admin-key.pem
    - aggregator.pem
    - aggregator-key.pem
  vars:
    src_path: /etc/kubernetes/pki
    dest_path: target/pki

- name: Fetch etcd client-certificates
  include_tasks: "{{ role_path }}/tasks/fetch_if_exists.yaml"
  with_items:
    - etcd.pem
    - etcd-key.pem
  vars:
    src_path: /etc/kubernetes/pki
    dest_path: target/pki/etcd
