prometheus:
  version: 2.27.1
  checksum: sha256:ce637d0167d5e6d2561f3bd37e1c58fe8601e13e4e1ea745653c068f6e1317ae
  query:
    max_samples: 10000000
    timeout: 10s

prometheus_retention: 4w

prometheus_jobs:
  - kubernetes-apiservers
  - kubernetes-cadvisor
  - kubernetes-service-endpoints
  - kubernetes-services
  - prometheus
  - prometheus-pushgateway
  - blackbox-exporter
  - blackbox-exporter-ingresses
  - tls-certificates
  - tls-certificates-kubernetes
  - jenkins
  - slo

prometheus_nais_namespaces:
  - nais
  - rook-ceph
  - loki
