prometheus:
  version: 2.9.2
  checksum: sha256:19d29910fd0e51765d47b59b9276df016441ad4c6c48e3b27e5aa9acb5d1da26
  query:
    max_samples: 10000000
    timeout: 10s

prometheus_retention: 4w

prometheus_jobs:
  - kubernetes-apiservers
  - kubernetes-cadvisor
  - kubernetes-nodes
  - kubernetes-service-endpoints
  - kubernetes-services
  - prometheus
  - prometheus-pushgateway
  - black box scraping of ingresses

prometheus_nais_namespaces:
  - nais
  - nais-rook
