prometheus:
  version: 2.26.0
  checksum: sha256:8dd6786c338dc62728e8891c13b62eda66c7f28a01398869f2b3712895b441b9
  query:
    max_samples: 10000000
    timeout: 10s

prometheus_retention: 4w

prometheus_jobs:
  - kubernetes-apiservers
  - kubernetes-cadvisor
  - kubernetes-service-endpoints
  - kubernetes-services
  - prometheus
  - prometheus-pushgateway
  - blackbox-exporter-ingresses
  - jenkins

prometheus_nais_namespaces:
  - nais
  - rook-ceph
  - loki
