prometheus:
  version: 2.20.1
  checksum: sha256:8fb248b579b8b9a88dd9b1686f7f68db7071960a45b28619145d3a4037375dcb
  query:
    max_samples: 10000000
    timeout: 10s

prometheus_retention: 4w

prometheus_jobs:
  - kubernetes-apiservers
  - kubernetes-cadvisor
  - kubernetes-service-endpoints
  - kubernetes-services
  - prometheus
  - prometheus-pushgateway
  - blackbox-exporter-ingresses
  - jenkins

prometheus_nais_namespaces:
  - nais
  - rook-ceph
  - loki
