prometheus:
  version: 2.7.1
  checksum: sha256:7837cfd6b5af63c07cadfa2b3118f0a43e43e8a6e6d596425cb23b45855b7db0
  retention: 4w
  query:
    max_samples: 10000000
    timeout: 10s

prometheus_jobs:
  - kubernetes-apiservers
  - kubernetes-cadvisor
  - kubernetes-nodes
  - kubernetes-service-endpoints
  - kubernetes-services
  - prometheus
  - prometheus-pushgateway
  - black box scraping of ingresses

prometheus_nais_namespaces:
  - nais
  - nais-rook
