# .bashrc

# User specific aliases and functions

alias rm='rm -i'
alias cp='cp -i'
alias mv='mv -i'
alias k='kubectl'
alias ks='kubectl --namespace kube-system'
alias kn='kubectl --namespace nais'

# Source global definitions
if [ -f /etc/bashrc ]; then
        . /etc/bashrc
fi
