groups:
- name: prometheus
  rules:
  - alert: PrometheusDiskUsage
    expr: 'predict_linear(node_filesystem_avail_bytes{instance="{{ inventory_hostname }}:9101",mountpoint="/data"}[8h], 3*24*60*60) < 0'
    for: 4h
    labels:
      alert: nais-nais-alerts
      cluster: {{ cluster_name }}
    annotations:
      description: {{ "'<!here> Prometheus is running low on disk space on {{ $labels.mountpoint }} on " }}{{ inventory_hostname }}{{ ", predicted empty in less than 3 days'" }}
      action: |
        Increase disk size / adjust retention / check for applications having an excessive number of metrics.
        Check for compaction errors in log, a restart might fix a corrupted segment blocking compaction.
  - alert: PrometheusDiskUsagePercent
    expr: '100 * node_filesystem_avail_bytes{instance="{{ inventory_hostname }}:9101",mountpoint!="/usr"} / node_filesystem_size_bytes{instance="{{ inventory_hostname }}:9101"} < 5'
    for: 5m
    labels:
      alert: nais-nais-alerts
      cluster: {{ cluster_name }}
    annotations:
      description: {{ "'<!subteam^SB8KS4WAV|nais-vakt> <!here> Less than 5% available disk space on {{ $labels.mountpoint }} on "}}{{ inventory_hostname }}{{ "'" }}
      action: |
        Increase disk size / adjust retention / check for applications having an excessive number of metrics.
        Check for compaction errors in log, a restart might fix a corrupted segment blocking compaction.
  - alert: PrometheusFederationDown
    expr: 'sum(up{instance="{{ cluster_prometheus_host }}:443",job=~"kubernetes-(apiservers|cadvisor|pods-a-m|pods-n-z)"}) < 4'
    for: 5m
    labels:
      alert: nais-nais-alerts
      cluster: {{ cluster_name }}
    annotations:
      description: {{ "'<!subteam^SB8KS4WAV|nais-vakt> <!here> Federation of in-cluster Prometheus failed'" }}
      action: 'Check status on Prometheus pod / try accessing https://{{ cluster_prometheus_host }}/'
  - alert: PrometheusReload
    expr: 'prometheus_config_last_reload_successful{job="prometheus-local"} < 1'
    for: 3m
    labels:
      alert: nais-nais-alerts
      cluster: {{ cluster_name }}
    annotations:
      description: {{ "'<!subteam^SB8KS4WAV|nais-vakt> <!here> Reloading of Prometheus config failed on " }}{{ inventory_hostname }}{{ "'" }}
      action: "Check Prometheus logs"
