groups:
- name: prometheus
  rules:
  - alert: PrometheusDiskUsage
    expr: 'predict_linear(node_filesystem_avail_bytes{instance="{{ inventory_hostname }}:9101"}[8h], 3*24*60*60) < 0'
    for: 2m
    labels:
      team: aura
      cluster: {{ cluster_name }}
    annotations:
      description: {{ "'<!subteam^SB8KS4WAV|nais-vakt> <!here> Prometheus is running low on disk space on {{ $labels.mountpoint }}, predicted empty in less than 3 days'" }}
      action: "Cleanup / increase disk size / adjust retention / check for applications having an excessive number of metrics"
  - alert: PrometheusDiskUsagePercent
    expr: '100 * node_filesystem_avail_bytes{instance="{{ inventory_hostname }}:9101"} / node_filesystem_size_bytes{instance="{{ inventory_hostname }}:9101"} < 5'
    for: 2m
    labels:
      team: aura
      cluster: {{ cluster_name }}
    annotations:
      description: {{ "'<!subteam^SB8KS4WAV|nais-vakt> <!here> Less than 5% available disk space on {{ $labels.mountpoint }}'" }}
      action: "Cleanup / increase disk size / adjust retention / check for applications having an excessive number of metrics"
