global:
  scrape_interval: 1m
  scrape_timeout: 50s
  evaluation_interval: 1m

scrape_configs:
  - job_name: 'prometheus-local'
    static_configs:
    - targets: ['localhost:9090']

  - job_name: 'nodes'
    static_configs:
      - targets:
        - localhost:9101
        labels:
          node_type: prometheus
      - targets:
{% for host in groups['masters'] %}
        - '{{ host }}:9101'
{% endfor %}
        labels:
          node_type: master
      - targets:
{% for host in groups['workers'] %}
        - '{{ host }}:9101'
{% endfor %}
        labels:
          node_type: worker
      - targets:
{% for host in groups['storage_nodes'] %}
        - '{{ host }}:9101'
{% endfor %}
        labels:
          node_type: storage
      - targets:
{% for host in groups['etcd'] %}
        - '{{ host }}:9101'
{% endfor %}
        labels:
          node_type: etcd

{% for job in prometheus_jobs %}
  - job_name: "{{ job }}"
    honor_labels: true
    metrics_path: '/federate'
    params:
      'match[]':
        - '{job="{{ job }}",kubernetes_namespace!="kube-system"}'
    scheme: https
    tls_config:
      insecure_skip_verify: true
    static_configs:
      - targets:
        - '{{ cluster_prometheus_host }}'
{% endfor %}

{% if cluster_scrape_jobs is defined %}
{% for job in cluster_scrape_jobs %}
  - job_name: "{{ job }}"
    honor_labels: true
    metrics_path: '/federate'
    params:
      'match[]':
        - '{job="{{ job }}"}'
    scheme: https
    tls_config:
      insecure_skip_verify: true
    static_configs:
      - targets:
        - 'prometheus.nais.{{ domain }}'
{% endfor %}
{% endif %}
